//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_FoodPort.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/FoodPort_Payment")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CustomerAccountBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAccountHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RestaurantAccountBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestaurantAccountHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestaurantAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TransactionAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidfromField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountCardNumber {
            get {
                return this.AccountCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountCardNumberField, value) != true)) {
                    this.AccountCardNumberField = value;
                    this.RaisePropertyChanged("AccountCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV {
            get {
                return this.CVVField;
            }
            set {
                if ((object.ReferenceEquals(this.CVVField, value) != true)) {
                    this.CVVField = value;
                    this.RaisePropertyChanged("CVV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CustomerAccountBalance {
            get {
                return this.CustomerAccountBalanceField;
            }
            set {
                if ((this.CustomerAccountBalanceField.Equals(value) != true)) {
                    this.CustomerAccountBalanceField = value;
                    this.RaisePropertyChanged("CustomerAccountBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAccountHolderName {
            get {
                return this.CustomerAccountHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAccountHolderNameField, value) != true)) {
                    this.CustomerAccountHolderNameField = value;
                    this.RaisePropertyChanged("CustomerAccountHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAccountNumber {
            get {
                return this.CustomerAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAccountNumberField, value) != true)) {
                    this.CustomerAccountNumberField = value;
                    this.RaisePropertyChanged("CustomerAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RestaurantAccountBalance {
            get {
                return this.RestaurantAccountBalanceField;
            }
            set {
                if ((this.RestaurantAccountBalanceField.Equals(value) != true)) {
                    this.RestaurantAccountBalanceField = value;
                    this.RaisePropertyChanged("RestaurantAccountBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RestaurantAccountHolderName {
            get {
                return this.RestaurantAccountHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RestaurantAccountHolderNameField, value) != true)) {
                    this.RestaurantAccountHolderNameField = value;
                    this.RaisePropertyChanged("RestaurantAccountHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RestaurantAccountNumber {
            get {
                return this.RestaurantAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RestaurantAccountNumberField, value) != true)) {
                    this.RestaurantAccountNumberField = value;
                    this.RaisePropertyChanged("RestaurantAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TransactionAmount {
            get {
                return this.TransactionAmountField;
            }
            set {
                if ((this.TransactionAmountField.Equals(value) != true)) {
                    this.TransactionAmountField = value;
                    this.RaisePropertyChanged("TransactionAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionDateField, value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((this.TransactionIDField.Equals(value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidTo {
            get {
                return this.ValidToField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidToField, value) != true)) {
                    this.ValidToField = value;
                    this.RaisePropertyChanged("ValidTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Validfrom {
            get {
                return this.ValidfromField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidfromField, value) != true)) {
                    this.ValidfromField = value;
                    this.RaisePropertyChanged("Validfrom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBankService")]
    public interface IBankService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/MakePayment", ReplyAction="http://tempuri.org/IBankService/MakePaymentResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        int MakePayment(FinalProject_FoodPort.ServiceReference1.Transaction trans);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/MakePayment", ReplyAction="http://tempuri.org/IBankService/MakePaymentResponse")]
        System.Threading.Tasks.Task<int> MakePaymentAsync(FinalProject_FoodPort.ServiceReference1.Transaction trans);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/CancelOrder", ReplyAction="http://tempuri.org/IBankService/CancelOrderResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        bool CancelOrder(int transid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/CancelOrder", ReplyAction="http://tempuri.org/IBankService/CancelOrderResponse")]
        System.Threading.Tasks.Task<bool> CancelOrderAsync(int transid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankServiceChannel : FinalProject_FoodPort.ServiceReference1.IBankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<FinalProject_FoodPort.ServiceReference1.IBankService>, FinalProject_FoodPort.ServiceReference1.IBankService {
        
        public BankServiceClient() {
        }
        
        public BankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int MakePayment(FinalProject_FoodPort.ServiceReference1.Transaction trans) {
            return base.Channel.MakePayment(trans);
        }
        
        public System.Threading.Tasks.Task<int> MakePaymentAsync(FinalProject_FoodPort.ServiceReference1.Transaction trans) {
            return base.Channel.MakePaymentAsync(trans);
        }
        
        public bool CancelOrder(int transid) {
            return base.Channel.CancelOrder(transid);
        }
        
        public System.Threading.Tasks.Task<bool> CancelOrderAsync(int transid) {
            return base.Channel.CancelOrderAsync(transid);
        }
    }
}
